/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComercioRouteImport } from './routes/comercio'
import { Route as SaudeRouteImport } from './routes/saude'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercioRoute = ComercioRouteImport.update({
  id: '/comercio',
  path: '/comercio',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudeRoute = SaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comercio': typeof ComercioRoute
  '/saude': typeof SaudeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comercio': typeof ComercioRoute
  '/saude': typeof SaudeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comercio': typeof ComercioRoute
  '/saude': typeof SaudeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comercio' | '/saude'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comercio' | '/saude'
  id: '__root__' | '/' | '/comercio' | '/saude'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComercioRoute: typeof ComercioRoute
  SaudeRoute: typeof SaudeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercio': {
      id: '/comercio'
      path: '/comercio'
      fullPath: '/comercio'
      preLoaderRoute: typeof ComercioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saude': {
      id: '/saude'
      path: '/saude'
      fullPath: '/saude'
      preLoaderRoute: typeof SaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComercioRoute: ComercioRoute,
  SaudeRoute: SaudeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
